server:
  port: 2000

spring:
   datasource:
      url: jdbc:mysql://b.yedaoholding.com:3306/core_devcn?useSSL=false&useUnicode=true&characterEncoding=utf-8
      name: root
      password:  mode2019
   data:
      redis:
         repositories:
            enabled: true
         host: b.yedaoholding.com
         databse: 1
         port: 6379
         timeout: 5000ms