server:
  port: 20002
eureka:
  server:
    eviction-interval-timer-in-ms: 1000   #设置清理的间隔时间，而后这个时间使用的是毫秒单位（默认是60秒）
  client:
    fetch-registry: false   # 是否注册
    register-with-eureka: false
    service-ui:
       defaultZone: http://localhost:20000,http://localhost:20001,http://localhost:20002
  instance:
    hostname: eureka2
